version: "3.8"

services:
  web:
    image: subscription_test_django
    env_file:
      - .local
    build:
      context: .
      dockerfile: chat_subscription/Dockerfile
    command: "python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - ./chat_subscription/:/code/chat_subscription/
      - ./manage.py:/code/manage.py
    networks:
      - subscription_test
    depends_on:
      - postgres
    
  postgres:
    restart: unless-stopped
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_HOST: postgres
      POSTGRES_DATABASE: postgres
      POSTGRES_USER: postgres
    env_file:
      - .local
    volumes:
      - postgresql_data:/var/lib/postgresql
      - /tmp:/backups
    networks:
      - subscription_test
    ports:
      - 5432:5432

volumes:
  postgresql_data:

networks:
  subscription_test:
    driver: bridge
    ipam:
      driver: default
